// Code generated by "stringer -type AggregateType agg.go"; DO NOT EDIT

package agg

import "fmt"

const _AggregateType_name = "CountSumAvgMaxMin"

var _AggregateType_index = [...]uint8{0, 5, 8, 11, 14, 17}

func (i AggregateType) String() string {
	if i < 0 || i >= AggregateType(len(_AggregateType_index)-1) {
		return fmt.Sprintf("AggregateType(%d)", i)
	}
	return _AggregateType_name[_AggregateType_index[i]:_AggregateType_index[i+1]]
}
