// Code generated by "stringer -type AggregateType"; DO NOT EDIT

package agg

import "fmt"

const _AggregateType_name = "CountCountallSumAvgMaxMin"

var _AggregateType_index = [...]uint8{0, 5, 13, 16, 19, 22, 25}

func (i AggregateType) String() string {
	if i < 0 || i >= AggregateType(len(_AggregateType_index)-1) {
		return fmt.Sprintf("AggregateType(%d)", i)
	}
	return _AggregateType_name[_AggregateType_index[i]:_AggregateType_index[i+1]]
}
